"""initial schema

Revision ID: 0e5a425c38cd
Revises: 
Create Date: 2026-08-11 11:02:35.021767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e5a425c38cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tld', sa.String(length=63), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currently_in_zone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domains_currently_in_zone'), ['currently_in_zone'], unique=False)
        batch_op.create_index(batch_op.f('ix_domains_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_domains_tld'), ['tld'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('zone_counts', sa.Text(), nullable=False),
    sa.Column('zone_transferred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_count', sa.Integer(), nullable=False),
    sa.Column('removed_count', sa.Integer(), nullable=False),
    sa.Column('returned_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)

    op.create_table('zone_snapshot_stats',
    sa.Column('tld', sa.String(length=63), nullable=False),
    sa.Column('name_count', sa.Integer(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('tld')
    )
    op.create_table('zone_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tld', sa.String(length=63), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name', name='uq_zone_staging_run_name')
    )
    with op.batch_alter_table('zone_staging', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_staging_run_id'), ['run_id'], unique=False)
        batch_op.create_index('ix_zone_staging_run_name', ['run_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_staging_tld'), ['tld'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=512), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_run_id'), ['run_id'], unique=False)

    op.create_table('domain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index('ix_domain_events_domain_type', ['domain_id', 'event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_run_id'), ['run_id'], unique=False)

    op.create_table('rule_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('domain_event_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('rule_description', sa.Text(), nullable=False),
    sa.Column('rule_pattern', sa.Text(), nullable=False),
    sa.Column('matched_value', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_event_id'], ['domain_events.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_matches_domain_event_id'), ['domain_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_matches_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_matches_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_matches_run_id'))
        batch_op.drop_index(batch_op.f('ix_rule_matches_domain_id'))
        batch_op.drop_index(batch_op.f('ix_rule_matches_domain_event_id'))

    op.drop_table('rule_matches')
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_domain_events_event_type'))
        batch_op.drop_index('ix_domain_events_domain_type')

    op.drop_table('domain_events')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_run_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('zone_staging', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_staging_tld'))
        batch_op.drop_index('ix_zone_staging_run_name')
        batch_op.drop_index(batch_op.f('ix_zone_staging_run_id'))

    op.drop_table('zone_staging')
    op.drop_table('zone_snapshot_stats')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_status'))

    op.drop_table('runs')
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domains_tld'))
        batch_op.drop_index(batch_op.f('ix_domains_name'))
        batch_op.drop_index(batch_op.f('ix_domains_currently_in_zone'))

    op.drop_table('domains')
    # ### end Alembic commands ###
