"""add run progress tracking

Revision ID: ad199208d139
Revises: c08363c47666
Create Date: 2026-08-22 14:41:55.613224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad199208d139'
down_revision: Union[str, Sequence[str], None] = 'c08363c47666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('phase', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('staged_hint', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_column('staged_hint')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('phase')
        batch_op.drop_column('pid')

    # ### end Alembic commands ###
