"""add typosquat scoring and ngram models

Revision ID: c08363c47666
Revises: 0e5a425c38cd
Create Date: 2026-08-16 13:38:23.168131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08363c47666'
down_revision: Union[str, Sequence[str], None] = '0e5a425c38cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngram_models',
    sa.Column('tld', sa.String(length=63), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('tld')
    )
    with op.batch_alter_table('rule_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('signals', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_rule_matches_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_matches_method'), ['method'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_matches_method'))
        batch_op.drop_index(batch_op.f('ix_rule_matches_brand'))
        batch_op.drop_column('signals')
        batch_op.drop_column('score')
        batch_op.drop_column('brand')
        batch_op.drop_column('method')

    op.drop_table('ngram_models')
    # ### end Alembic commands ###
